language: c

compiler:
  - clang
  - gcc

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - check
      - libxml2-dev
      - libshout-dev
      - libtagc0-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
